gantt
    title Ablauf Test-Wall
    dateFormat  YYYY-MM-DD
    section Vor Einbau
    Anzahl Bauteile           :a1, 2024-05-01, 3d
    Layout machen     :a2, 2024-05-03  , 4d
    Grösse Schrank überprüfen :a3, 2024-05-08, 1d
    section Schrank Passt
    Befestigungsmaterial bestellen      :b1, 2024-05-09 , 1d
    Recks einbauen      :after b1, 6d
    section Schrank passt nicht
    Masse Berechnen und Schrank & Befestigungsmaterial bestellen :after a3, 1d
    Recks einbauen :c1, after b1, 7d
    section B-Learning
    Learning 1 & 2 :d1, 2024-05-06, 1d
